version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: price_alert_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    command: celery -A price_alerts worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A price_alerts beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
